### PR TITLE
All System Tests Have Been Refactored and Workability of Testcontainers Has Been Refactored

### PR DESCRIPTION
**Pull request by agitrubard**
### Description

- [X] Application Parameters Have Been Updated in application.yml File
- [X] Unused Classes Have Been Deleted
- [X] All Test Data Have Been Refactored
- [X] All System Tests Have Been Refactored and Workability of Testcontainers Has Been Refactored
- [X] Verify Step Has Been Added to All Test Cases
- [X] `static` Keyword Has Been Removed from Mappers

### Checklist

Please check the following before submitting your pull request:

- [X] I have tested my changes locally and they are working as expected.
- [X] The code is formatted according to the project's coding guidelines and style.
- [X] Necessary documentation has been added or existing documentation has been updXted.
- [X] Relevant unit tests have been written and included.
- [X] Relevant integration tests have been written and included.
- [X] The code has been reviewed to ensure its quality.
- [X] The code does not contain any issues flagged by SonarLint.
- [X] Default reviewers have been assigned to this pull request.
- [X] Assignees have been added if necessary.
- [X] Labels have been applied if necessary.
- [x] If an issue is opened and this pull request is related to that issue, it should not be associated with any project
  board or milestone. However, if there is no issue, the pull request should be associated with the appropriate project
  board (BE Board, In Review column) and milestone to track the progress.

### CODE REVIEW

**Review by emreylmaz — DISMISSED** [review]
Localde testlerimiz sorunsuz çalışıyor. Pipeline build başarılı. ✅ Eline sağlık.

**Review by Rapter1990 — DISMISSED** [review]
Branch de gelip tüm testleri çalıştırdım. Tüm testler çalışıyor. Herhangi bir sorun yok. CI/CD de caçlışıyor. Güzel bir çalışma olmuş. Eline sağlık. ✅

**Review by AhmetAksunger — DISMISSED** [review]
Eline sağlık.

**Review by emreylmaz — APPROVED** [review]
Refactor ✅

**Pull request merged**
