### PR TITLE
Add docker-compose.yml and k8s deployment.yaml and service.yaml files

### PR DESCRIPTION
**Pull request by halilturkoglucs**
These files can both be used for local development and deployment to the cloud.

### CODE REVIEW

**Review by skayikci — CHANGES_REQUESTED** [review]
- there's a problem regarding the java image that we use here, the problem is:
 it is not able to load for macbook pro with M1 chips. 
Therefore we need to use this version: azul/zulu-openjdk:17 in order to comply with those kind of machines. Here is the error that i'm having: 
 => ERROR [internal] load metadata for docker.io/library/eclipse-temurin:17-jdk-alpine                                                                                                                     1.8s
------
 > [internal] load metadata for docker.io/library/eclipse-temurin:17-jdk-alpine:
 failed to solve: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0: failed to create LLB definition: no match for platform in manifest sha256:b99f9457ad5cabdfa02935d1048082dd79d318685cfa0ca79a8f623c052c406a: not found
------



- secondly, do we want to load the whole database locally? Or we can just switch to h2 locally, as we talked before, if so, then we need to switch the profile to dev: "SPRING_PROFILES_ACTIVE=dev". 

- third point is about the folder structure, all the files are under the root folder, and for different kind of profiles, we won't have the possibility to change it when we don't have different files for those envs.

**Comment by halilturkoglucs** [comment]
1. I think you fixed it with another pr, so it should work fine now.
2. Hmm, it may depend on the situation but normally mysql db should be considered (for docker compose case), other in-mem solutions may not be indicated in k8s or compose files. So maybe here we can add active profile config to .env.local instead to make it dynamic, ill make this change.
3. I think for now root dir is the convention. However i do agree that these files may be configurable depending on the env. So, i propose tackling this with another pr which should add helm or koncig k8s templating solutions. For this, we need to also first agree on using helm or another tool

**Comment by halilturkoglucs** [comment]
@skayikci i've added spring profiles to docker-compose.yaml, if it looks good to you, we can merge and i can tackle env separation for k8s in a seperate PR after backend agrees on the tool to use

**Comment by skayikci** [comment]
Could you also add the image that fixes the problem with m1 chips? I opened the pr to test something.

**Comment by halilturkoglucs** [comment]
@skayikci sure, done

**Review by skayikci — APPROVED** [review]
lgtm

**Pull request merged**
