### PR TITLE
`CODEOWNERS` and `README.md` Files Have Been Updated

### PR DESCRIPTION
**Pull request by agitrubard**

### CODE REVIEW

**Comment by Rapter1990** [comment]
LGTM. Thank you for your work.

**Review by skayikci — APPROVED** [review]

**Review by Rapter1990 — APPROVED** [review]

**Comment by Rapter1990** [comment]
@agitrubard I just approved it. You can merge it.

**Comment by haliltrk** [comment]
I think rather than assigning certain people as codeowners, you can either add a sub-team and state it here or leave as-is

**Comment by agitrubard** [comment]
> I think rather than assigning certain people as codeowners, you can either add a sub-team and state it here or leave as-is


In the review process, we have decided to consider project standards and prevent non-compliant merge operations. We will continue by adding active developers who have a good understanding of the project to the review process. It will not be limited to just these three individuals. If we accept the review approval of individuals who are not familiar with the project standards, it could potentially disrupt the project standards, and it might be challenging to rectify the situation. That's why I made this decision. If there are any aspects or points that I haven't explained or might have missed, we can discuss them to clarify further.

**Comment by haliltrk** [comment]
Okay sounds fine then

**Pull request merged**
