### PR TITLE
Permission of Actuator

### PR DESCRIPTION
**Pull request by Rapter1990**
What I have done in the security config to give a permission to /actuator to access its features

### CODE REVIEW

**Review by skayikci — CHANGES_REQUESTED** [review]
please make sure to limit the access to the super admins only.

**Comment by skayikci** [comment]
please provide the necessary test cases to test the behaviours.

**Comment by Rapter1990** [comment]
@skayikci  
I'll revise the line as shown below

`.antMatchers(HttpMethod.GET,"/actuator/**").hasRole("SUPER_ADMIN")`

**Comment by Rapter1990** [comment]
@skayikci 
`testActuatorEndpointsAccessWithUserRole` method produces 200 Ok instead of 403 Forbidden.

**Review by agitrubard — APPROVED** [review]

**Review by skayikci — APPROVED** [review]

**Comment by skayikci** [comment]
The problem occurs for the same reason as refresh token exchange endpoints. Please have a look when  you are working on refactoring.

**Pull request merged**
